services:
  - type: web
    name: kintox
    runtime: node
    rootDir: .
    buildCommand: npm install && npm run build && cp -r dist server/dist
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CONTACT_EMAIL
        value: nakshtr.144@gmail.com
      - key: GROQ_API_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://e-kintox-1.onrender.com
      - key: VERIFICATION_URL
        value: https://e-kintox-1.onrender.com
